# Generated by Django 2.1.7 on 2019-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id_tipoexame', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipoexame', models.TextField()),
            ],
        ),
    ]
